title: "Nisarg Nigam Portfolio"
theme: minima

header_pages:
  - index.md
  - masters-project.md
  - research.md
  - resume.md

# Make sure assets folder is included in the site build
include:
  - assets
